- id: "/"
  title: "Estudiantes RSEF"
  description: "El Grupo de Estudiantes de la Real Sociedad Española de Física busca reunir a todos los estudiantes de física de España, proporcionarles nuevas oportunidades a nivel nacional e internacional y ayudar a mejorar la divulgación de la física y su enseñanza. Estudiantes RSEF es National Committee Spain en la International Association of Physics Students (IAPS)."
  keywords: "estudiantes rsef iaps"
- id: "/eventos/"
  title: "Estudiantes RSEF - Eventos"
  description: "Estudiantes RSEF organiza eventos de carácter local, nacional e internacional para sus miembros: conferencias, visitas a laboratorios o charlas de estudiantes, investigadores y profesores."
  keywords: "estudiantes rsef iaps"
